### ISSUE TITLE
Support for elasticsearch[async]

### ISSUE THREAD

**Issue by alikaz3mi** [langchain-ai/langchain-elastic#33]
Does this repository support for async version of elasticsearch database?

**Comment by miguelgrinberg** [comment]
No, we have not implemented async interfaces.

**Comment by alikaz3mi** [comment]
Thanks. Do you have any plans for adding it to langchain?

**Comment by miguelgrinberg** [comment]
Our Elasticsearch Python client libraries do have async support, but I believe this is the first request we get for async support in the langchain integration. I will pass the request on.

**Comment by giacbrd** [comment]
Hi @miguelgrinberg , regarding the PR mentioned above, are you planning to tag it for the PR review process?
I am just asking, no pressure!

**Comment by miguelgrinberg** [comment]
@giacbrd What is the reasoning behind the idea to support sync and async in a single set of classes, especially given that we do not support async in this way in the Elasticsearch client?

**Comment by giacbrd** [comment]
@miguelgrinberg The class `ElasticsearchStore` extends the LangChain abstract class [VectorStore](https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/vectorstores/base.py#L57) that has both sync and async methods in the same abstraction. However async methods are merely implemented in a "sync" way, i.e. [asimilarity_search_with_score](https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/vectorstores/base.py#L464). 

The PR proposes a correct implementation of these methods for `ElasticsearchStore`, by integrating the `AsyncVectorStore` of the Elasticsearch python library. 

Currently, if one wants to use async is forced to bypass [langchain-elastic](https://github.com/langchain-ai/langchain-elastic) and and use directly the `AsyncVectorStore` in [elasticsearch-py](https://github.com/elastic/elasticsearch-py). This PR should solve this problem, and allow developers to exploit LangChain for vector search.

**Comment by miguelgrinberg** [comment]
@giacbrd I understand this, but why not create a separate `AsyncElasticsearchStore` class that also inherits from Langchain's `VectorStore` and implements the "a" methods properly? You will never need to use both sync and async together, anyway.

**Comment by miguelgrinberg** [comment]
@giacbrd the problem is that we have developed a system to deal with async vs sync that works very well for us and we like, and in my opinion is far superior to the way other Langchain integrations such as the two you linked are designed. Given that this is an integration that we support directly and we have people who have spent a considerable amount of time and effort to create a clean, workable solution for our Python packages what would make most sense for us is to add async support using our solution. But this is something that I'll bring up to discuss internally, to see how the team feels.

**Comment by giacbrd** [comment]
@miguelgrinberg sorry maybe I do not perfectly understand the context. When you refer to your solution do you mean this https://github.com/elastic/elasticsearch-py/blob/main/elasticsearch/helpers/vectorstore/_async/vectorstore.py ? What I have developed is just a "wrapper" to this class, in order to have an interface compatible with all other LangChain VectorStore implementations, e.g. for using it in a LangChain RAG chain

**Comment by miguelgrinberg** [comment]
@giacbrd no. We have a solution to create Python packages that support async and sync without having to write everything twice.

**Comment by giacbrd** [comment]
@miguelgrinberg Interesting, is your solution available? Do you use it in some open source project? I suppose the problem with this package is to keep the compatibility with the VectorStore interface, without breaking the design pattern of LangChain

**Comment by miguelgrinberg** [comment]
@giacbrd Yes, our solution is based on the use of [unasync](https://github.com/python-trio/unasync), which generates sync code by parsing the async code and automatically converting it.

**Comment by miguelgrinberg** [comment]
@giacbrd I have added https://github.com/langchain-ai/langchain-elastic/pull/53 with an initial attempt to support async in the entire library (not just the vector store). It may take me some time to get the CI passing fully, but the basic structure is done. The idea is that for each integration class there is a `Class` and `AsyncClass`. If you use the latter, you use the "a" methods. With the former you use the regular methods.

**Comment by miguelgrinberg** [comment]
#53 is merged
